PayCalculator/PayCalculatorMVC/Controllers/PermanentEmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using PayCalculatorLibrary.Models;
using PayCalculatorLibrary.Repositories;
using PayCalculatorLibrary.Services;
using PayCalculatorMVC.Models;

namespace PayCalculatorMVC.Controllers
{
    public class PermanentEmployeeController : Controller
    {
        private readonly ILogger<PermanentEmployeeController> _logger;
        private readonly IEmployeeRepository<PermanentEmployee> _permEmployeeRepo;
        private readonly IPermanentEmployeeMapper _mapper;
        private readonly IPermanentPayCalculator _payCalculator;
        private readonly ITimeCalculator _timeCalculator;

        public PermanentEmployeeController(ILogger<PermanentEmployeeController> logger, IEmployeeRepository<PermanentEmployee> permEmployeeRepo, 
            IPermanentEmployeeMapper mapper, IPermanentPayCalculator calculator, ITimeCalculator timeCalculator)
        {
            _logger = logger;
            _permEmployeeRepo = permEmployeeRepo;
            _mapper = mapper;
            _payCalculator = calculator;
            _timeCalculator = timeCalculator;
        }

        public IActionResult Index(PermEmployeeAlertsViewModel viewModel)
        {
            var employeeList = _permEmployeeRepo.GetAll();
            viewModel.Employees = employeeList;

            if (!viewModel.Alerts.HasValue)
            {
                viewModel.Alerts = Enums.Alerts.None;
            }

            foreach (var employee in employeeList) 
            {
                employee.HoursWorked = _timeCalculator.HoursWorked(employee.StartDate, DateTime.Now);
                employee.TotalAnnualPay = Math.Round(_payCalculator.TotalAnnualPay(employee.Salary.Value, employee.Bonus.Value), 2);
                employee.HourlyRate = Math.Round(_payCalculator.HourlyRate(employee.Salary.Value, employee.HoursWorked), 2);
            }

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateOrUpdatePermanentEmployee createModel)
        {
            var mappedEmployee = _mapper.Map(createModel);
            var viewModel = new PermEmployeeAlertsViewModel();
            viewModel.Name = createModel.Name;

            if (ModelState.IsValid)
            {
                _permEmployeeRepo.Create(mappedEmployee);
                viewModel.Alerts = Enums.Alerts.CreateSuccess;
                return RedirectToAction("Index", viewModel);
            }

            return View(mappedEmployee);
        }

        public IActionResult Update(int id)
        {
            var employee = _permEmployeeRepo.GetEmployee(id);
            return View(employee);
        }

        [HttpPost]
        public IActionResult Update(PermanentEmployee existingEmployee)
        {
            var viewModel = new PermEmployeeAlertsViewModel();
            var updated = _permEmployeeRepo.Update(existingEmployee);

            if (updated != null)
            {
                viewModel.Name = updated.Name;
            }

            if (ModelState.IsValid)
            {
                _permEmployeeRepo.Update(existingEmployee);
                viewModel.Alerts = Enums.Alerts.UpdateSuccess;
                return RedirectToAction("Index", viewModel);
            }

            return RedirectToAction("Update");
        }

        public IActionResult Delete(int id)
        {
            var employee = _permEmployeeRepo.GetEmployee(id);
            return View(employee);
        }


        [HttpPost]
        public IActionResult Deletion(int id)
        {
            var viewModel = new PermEmployeeAlertsViewModel();
            viewModel.Name = _permEmployeeRepo.GetEmployee(id).Name;
            var delete = _permEmployeeRepo.Delete(id);

            if (!delete)
            {
                viewModel.Alerts = Enums.Alerts.DeleteFailure;
                return RedirectToAction("Index", viewModel);
            }

            _permEmployeeRepo.Delete(id);
            viewModel.Alerts = Enums.Alerts.DeleteSuccess;
            return RedirectToAction("Index", viewModel);
        }
    }
}

PayCalculator/PayCalculatorMVC/Controllers/TemporaryEmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using PayCalculatorLibrary.Models;
using PayCalculatorLibrary.Repositories;
using PayCalculatorLibrary.Services;
using PayCalculatorMVC.Models;

namespace PayCalculatorMVC.Controllers
{
    public class TemporaryEmployeeController : Controller
    {
        private readonly ILogger<TemporaryEmployeeController> _logger;
        private readonly IEmployeeRepository<TemporaryEmployee> _tempEmployeeRepo;
        private readonly ITemporaryEmployeeMapper _mapper;
        private readonly ITemporaryPayCalculator _payCalculator;
        private readonly ITimeCalculator _timeCalculator;

        public TemporaryEmployeeController(ILogger<TemporaryEmployeeController> logger, IEmployeeRepository<TemporaryEmployee> tempEmployeeRepo,
            ITemporaryEmployeeMapper mapper, ITemporaryPayCalculator calculator, ITimeCalculator timeCalculator)
        {
            _logger = logger;
            _tempEmployeeRepo = tempEmployeeRepo;
            _mapper = mapper;
            _payCalculator = calculator;
            _timeCalculator = timeCalculator;
        }

        public IActionResult Index(TempEmployeeAlertsViewModel viewModel)
        {
            var employeeList = _tempEmployeeRepo.GetAll();
            viewModel.Employees = employeeList;

            if (!viewModel.Alerts.HasValue)
            {
                viewModel.Alerts = Enums.Alerts.None;
            }

            foreach (var employee in employeeList)
            {
                employee.HoursWorked = _timeCalculator.HoursWorked(employee.StartDate, DateTime.Now);
                employee.WeeksWorked = _timeCalculator.WeeksWorked(employee.StartDate, DateTime.Now);
                employee.TotalAnnualPay = Math.Round(_payCalculator.TotalAnnualPay(employee.DayRate, employee.WeeksWorked), 2);
                employee.HourlyRate = Math.Round(_payCalculator.HourlyRate(employee.DayRate), 2);
            }

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateOrUpdateTemporaryEmployee createModel)
        {
            var mappedEmployee = _mapper.Map(createModel);
            var viewModel = new TempEmployeeAlertsViewModel();
            viewModel.Name = createModel.Name;

            if (ModelState.IsValid)
            {
                _tempEmployeeRepo.Create(mappedEmployee);
                viewModel.Alerts = Enums.Alerts.CreateSuccess;
                return RedirectToAction("Index", viewModel);
            }

            return RedirectToAction("Create");
        }

        public IActionResult Update(int id)
        {
            var employee = _tempEmployeeRepo.GetEmployee(id);
            return View(employee);
        }

        [HttpPost]
        public IActionResult Update(TemporaryEmployee existingEmployee)
        {
            var viewModel = new TempEmployeeAlertsViewModel();
            var updated = _tempEmployeeRepo.Update(existingEmployee);

            if (updated != null)
            {
                viewModel.Name = updated.Name;
            }

            if (ModelState.IsValid)
            {
                _tempEmployeeRepo.Update(existingEmployee);
                viewModel.Alerts = Enums.Alerts.UpdateSuccess;
                return RedirectToAction("Index", viewModel);
            }

            return RedirectToAction("Update");
        }

        public IActionResult Delete(int id)
        {
            var employee = _tempEmployeeRepo.GetEmployee(id);
            return View(employee);
        }

        [HttpPost]
        public IActionResult Deletion(int id)
        {
            var viewModel = new TempEmployeeAlertsViewModel();
            viewModel.Name = _tempEmployeeRepo.GetEmployee(id).Name;
            var delete = _tempEmployeeRepo.Delete(id);

            if (!delete)
            {
                viewModel.Alerts = Enums.Alerts.DeleteFailure;
                return RedirectToAction("Index", viewModel);
            }

            _tempEmployeeRepo.Delete(id);
            viewModel.Alerts = Enums.Alerts.DeleteSuccess;
            return RedirectToAction("Index", viewModel);
        }
    }
}

PayCalculator/PayCalculatorMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PayCalculatorMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PayCalculatorMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PayCalculatorMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="PermanentEmployee" asp-action="Index">PermanentEmployee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="TemporaryEmployee" asp-action="Index">TemporaryEmployee</a>
                        </li>
                    </ul>
                </div>
                <form id="search-bar" class="d-flex" role="search">
                    <input class="form-control me-2 bg-dark btn-outline-secondary text-light" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted d-flex">
        <div class="container">
            &copy; 2023 - PayCalculatorMVC - <a asp-area="" asp-controller="PermanentEmployee">PermanentEmployee</a>
        </div>
        <div class="container">
            &copy; 2023 - PayCalculatorMVC - <a asp-area="" asp-controller="TemporaryEmployee">TemporaryEmployee</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>